### ISSUE TITLE
Missing database links

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#120]
Not sure if this is distinct from the broken links in #112 but some sequences appear to have no database links. For example:

http://rnacentral.org/rna/URS00000003C7/4896

Has no listed expert databases. That said it does claim that it is found in a single DB, ENA, while no ENA xrefs are listed.

**Comment by blakesweeney** [comment]
There are several sequences with this, or a similar issue. For example:

http://rnacentral.org/rna/URS00002228FD/4896
http://rnacentral.org/rna/URS00001E9E77/4896
http://rnacentral.org/rna/URS00000FE5AF/4896
http://rnacentral.org/rna/URS00001E9E77/4896

and so forth all claim to be found in 2 databases (or more) and do not have that many annotations. The missing annotations always come from ENA. I suspect this is due to some suppressed or deleted ENA entries whose's state is not being correctly dealt with at the display level. Also, all these sequences are labeled 'predicted' as well.

**Comment by AntonPetrov** [comment]
The first sequence is indeed wrong and should be looked at but the second one is actually correct. [URS00002228FD/4896](http://rnacentral.org/rna/URS00002228FD/4896) has a PomBase link and a source ENA link. 

This happens when databases are imported via TPAs (Third Party Annotations), so one row in the Annotations table corresponds to two xrefs. I agree that this might be confusing. Maybe not show the ENA link at all? On the other hand, sometimes those ENA links are useful.

**Comment by blakesweeney** [comment]
Maybe just not show the names of the databases if there is no link in the annotation section. There would still be the source ENA link as well. Still, that is confusing in a different way. Maybe it could be fixed with different labelling?

**Comment by AntonPetrov** [comment]
This has been resolved by the new import pipeline.
