### ISSUE TITLE
URLs for invalid species-specific forms of an RNA give a 200 response (test server)

### ISSUE THREAD

**Issue by cmungall** [RNAcentral/rnacentral-webcode#22]
URS000075C808 is specific to Homo sapiens (9606)

This URL
 * http://test.rnacentral.org/rna/URS000075C808/10090

Gives a `200` and resolves to HTML stating that it's actually showing me $rna/9606

I believe a `30x` and a redirect to $rna/9606 would be more appropriate

OR a `404` "not found" ...which is what the API gives me:
 * http://test.rnacentral.org/api/v1/rna/URS000075C808/10090

I realize this is the test server,  this is a "hope this helps" ticket rather than "I must have this fixed", cheers.

I'm also interested in what the canonical form of the species-specific ID is (slash or underscore) but will email Alex directly, just FYI

**Comment by foreveremain** [comment]
+1 (and if you get any sense from Alex re your query... +1 for that too :D )

**Comment by AntonPetrov** [comment]
Thanks for this report. I agree, the response is inconsistent. 

In my view a request for a non-existent id like *URS000075C808/10090* should redirect to *URS000075C808* (not sure if it should go directly to *URS000075C808/9606* because there may be more species in other cases) or show a ``404``. I'll fix this and close the issue when the test server is updated.

The preferred format for the species-specific ids is with a slash, but ids with underscores should work too.

**Comment by AntonPetrov** [comment]
This should be fixed now. I opted for redirecting to non-species specific URS pages when a taxid is not found.

For example, 
http://test.rnacentral.org/rna/URS000075C808/10090

now redirects to 
http://test.rnacentral.org/rna/URS000075C808

with a warning message: ``No annotations from taxid:10090.``

Please feel free to reopen this issue if you have further suggestions.
