### ISSUE TITLE
alternate spliceforms and GFF3 downloads

### ISSUE THREAD

**Issue by cmungall** [RNAcentral/rnacentral-webcode#43]
Curious as to why the page for URS000075EF05 doesn't have a GFF download

Also, the GFF3 FTP download has the spliceforms but not the gene:
```
12      RNAcentral      transcript      53962453        53963973        .       -       .       ID=NR_003716.3:1..2364:ncRNA;Name=URS000075C808;type=lncRNA
12      RNAcentral      noncoding_exon  53962453        53963973        .       -       .       ID=NR_003716.3:1..2364:ncRNA_exon1;Name=URS000075C808;Parent=NR_003716.3:1..2364:ncRNA;type=lncRNA
```
The id URS000075EF05 is not in the GFF3 file 

GFF3 allows and has a canonical gene model where alt transcripts are grouped into a gene entry, might be useful to include this

**Comment by AntonPetrov** [comment]
Hi Chris,

In order to get genome coordinates for an entry, we check if the underlying INSDC accessions are part of the reference genome, and the [RefSeq entry](http://www.ncbi.nlm.nih.gov/nuccore/NR_047518) that you mentioned is only partly based on the reference human genome.

If you look at a [Vega entry](http://rnacentral.org/rna/URS0000301B08) from the same genomic location, you will notice that there are three shorter transcripts that all come from RefSeq:

![screen shot 2015-11-02 at 11 54 25](https://cloud.githubusercontent.com/assets/432675/10881180/9c5fecba-8158-11e5-890c-f9566ebd30c7.png)

Since we don't have the genomic coordinates for all exons in these RefSeq transcripts, they are not included in the GFF files. 

In the future we plan to do sequence-based mapping to reference genomes (using Blast or similar methods), so that more entries can be put in their genomic context.

Thanks for the suggestion about the gene GFF entries. As far as I remember, it has already been implemented and should become available in the next RNAcentral release.

**Comment by AntonPetrov** [comment]
This is now fixed, see http://rnacentral.org/rna/URS000075EF05/9606
