### ISSUE TITLE
Shall we ask EBI search to change labels on 'has_conserved_structure', 'has_go_annotations', 'qc_warnings_found' and 'qc_warning found'?

### ISSUE THREAD

**Issue by BurkovBA** [RNAcentral/rnacentral-webcode#457]
Currently we're explicitly renaming labels of the following facets on the frontend:

[
  'has_conserved_structure',
  'has_go_annotations',
  'qc_warnings_found',
  'qc_warning found'
]

https://github.com/RNAcentral/rnacentral-webcode/blob/53bfda79b5be8976499a07a1226823fcfffc60c3/rnacentral/portal/static/js/components/text-search/text-search.service.js#L324

I don't want to duplicate this codebase in sequence search and text search.

Maybe we should stick with these new labels everywhere?

**Comment by AntonPetrov** [comment]
I would prefer to have the ability to rename the facets in front end
because we had to rename them quite a few times in the past year and it
would be unreasonable to have to email www-prod each time and wait for
hours/days until the changes are applied.

Le mer. 10 avr. 2019 à 17:23, Boris Burkov <notifications@github.com> a
écrit :

**Comment by BurkovBA** [comment]
Ok, we can keep this whole function for renames.

But doesn't it make sense to ask search guys to change the names? Cause this list can grow on and on, what's the point of expanding it indefinitely and repeating the labels everywhere?
