### ISSUE TITLE
Display expression atlas data in RNAcentral

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#554]
Expression atlas (https://www.ebi.ac.uk/gxa/home) has embeddable widgets that show expression of various lncRNAs in various cell types. See the FAQ at: https://www.ebi.ac.uk/gxa/FAQ.html for details. But we should show these widgets whenever possible as well as providing links to their site.

**Comment by carlosribas** [comment]
I've added the [Expression Atlas widget](https://www.npmjs.com/package/@ebi-gene-expression-group/expression-atlas-heatmap-highcharts) on our test website. Here is one example: https://test.rnacentral.org/rna/URS0000162127/9606

However, the widget has different types of views and I'm not sure which one is best for our use case. I believe we can use the widget as described [here](https://www.ebi.ac.uk/gxa/resources/test/widget/showcase/simple-search/H_sapiens-ENSG00000066279-Plain_text.html) or [here](https://www.ebi.ac.uk/gxa/resources/test/widget/showcase/reference-experiment/M_musculus-ASPM.html). Though I saw no difference in results for the pages I tested. In addition, the annotogram and results on some pages are not displayed correctly, but I'm not sure why, I still need to investigate, here is an [example](https://test.rnacentral.org/rna/URS00000478B7/9606).

**Comment by blakesweeney** [comment]
Great work, I'm very happy to see this on our test site! I think this display:

https://www.ebi.ac.uk/gxa/resources/test/widget/showcase/simple-search/H_sapiens-ENSG00000066279-Plain_text.html

is the one we want. If I understand the difference the other one shows data from
just one experiment, which is not what we want. We want the data from experiments
not just one (how is the 1 chosen anyway?).

**Comment by blakesweeney** [comment]
I think this is where @afg1 can chime in with how he loaded the mapping from URS to experiment ids into our database. I think you could use those experiments or the gene names I think he pulled out to build those queries.

**Comment by afg1** [comment]
That is cool! 

So for the import I grabbed all experiments and extracted the gene IDs from them then did a lookup to our database to find the corresponding URS. What we have is then an entry per URS which may reference any number of experiments. I also did some checking to make sure I was looking at the right organism - when you say you see 25 experiments for SRP RNA as a gene ID is that all in the right organism? 

I had thought the all experiments were represented in the url field, but it looks like only 1 is. I'll address that, because we should link to all of them really. Anyway, using the geneId which is in the externalId column should get you all experiments that reference that gene, is that what you want?
