### ISSUE TITLE
Filtering for some GO terms

### ISSUE THREAD

**Issue by beginner984** [RNAcentral/rnacentral-webcode#563]
Hi

I got a question which I was not able to solve yet

If I am only interested in lncRNAs related to `Angiogenesis GO term` how to download such a list please?

I searched for `Angiogenesis` in search bar and some results came out and I see for instance 123 of lncRNAs are here and I want to download them as a list but I don't know how

![Untitled](https://user-images.githubusercontent.com/43682980/135614592-6e64ebc9-2825-443b-a8c3-1e8ad7b198b6.jpg)

**Comment by AntonPetrov** [comment]
@beginner984 Thank you for your question! Currently you can download search results as FASTA or JSON files or as a list of RNAcentral IDs:

<img width="187" alt="Screenshot 2021-10-01 at 16 20 01" src="https://user-images.githubusercontent.com/432675/135645503-420bfc2b-e0aa-4dbd-a2bc-b8aae6232a3f.png">

I would like to note that when you search with a term like `Angiogenesis`, you will find all entries that mention angiogenesis, not only those annotated with an angiogenesis-related GO term. 

You will also notice that most of the results in your search are microRNAs. This is because they are the best-annotated sequences. In fact, there are several groups that manually annotate microRNAs with GO terms using RNAcentral IDs.

I do have a suggestion that you may find helpful. If you search for `pub_title:"angiogenesis"` you will see additional entries where the term `angiogenesis` occurs in one of the associated publication titles. 

https://rnacentral.org/search?q=pub_title:%22angiogenesis%22%20AND%20so_rna_type_name:%22LncRNA%

<img width="1169" alt="Screenshot 2021-10-01 at 16 12 54" src="https://user-images.githubusercontent.com/432675/135644585-d84c3f55-16b8-4106-96c3-09acfde9e2db.png">

The `pub_title` field is not searched by default because through experience we found that such results are not always relevant, so you might want to inspect the results with additional care.

I hope this helps!

**Comment by beginner984** [comment]
Thank you so much for your help

I am not much familiar with JASON or FASTA

In a forum somebody helped to download the results in such a format as I attached by link

http://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/database_mappings/gencode.tsv

Is the anyway to download the results in this format please?

**Comment by AntonPetrov** [comment]
I am afraid the tsv format is not supported in the text search export because RNAcentral entries have a lot of data and the tsv format is not flexible enough to represent it.

What information are you trying to extract? Ensembl IDs for any of the matching sequences?

**Comment by AntonPetrov** [comment]
Okay, I see. Currently there is no way to download this info from the web interface but it can be done using the  `id_mapping.tsv.gz` file that contains all external IDs linked to each `URS` accession:
http://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/

You can search this file with a tool like `grep` or by writing a script. Alternatively, you can connect to the public Postgres database and write an SQL query but that also requires some programming.

I can do this for you as a one-off task if you send me a URL of a search result that you want exported in this format.

**Comment by beginner984** [comment]
Thanks a million

I have attached a list of lncRNA here

Is it possible to get from this list any lncRNA related to angiogenesis and immune response please?
[d.txt](https://github.com/RNAcentral/rnacentral-webcode/files/7277846/d.txt)

**Comment by beginner984** [comment]
hank you so much

Might be non sense, do you know a software giving pathways related to a list of lncRNAs ?

I found LncPath R package which uses a networks of lncRNA-mRNA for getting pathways

Have you heard about a software directly giving pathways or GO terms related to a list of lncRNAs please?

In RNAcentral if we search for a lncRNA we may find a related GO term but this demands one by one checking 🙁

Thanks a lot anyway

**Comment by AntonPetrov** [comment]
In general I would not recommend using RNAcentral for lncRNA GO annotations, the coverage is very far from comprehensive at the moment. It's okay for microRNAs but not lncRNAs.

I have not used it but you could try [LncSEA](http://bio.liclab.net/LncSEA/) for lncRNA GO enrichment analysis.

Sorry that I cannot help more!

**Comment by beginner984** [comment]
Thanks a million

**Comment by AntonPetrov** [comment]
No worries, let us know if we can help with anything else.
