### ISSUE TITLE
Publish GPI file for RNCA

### ISSUE THREAD

**Issue by cmungall** [RNAcentral/rnacentral-webcode#58]
in #42 RNAC provided an ID mapping file with lots of useful metadata, thanks!

But RNAC also provide a secret GPI file:

ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/.gpi/rnacentral.gpi.gz

Are there plans to make this a part of the release? This would be preferable to us as we're using GPIs elsewhere

@tonysawfordebi, do you know anything about this?

**Comment by AntonPetrov** [comment]
The GPI file is updated every release, so it is already part of the release process, and in principle it could be distributed more openly. As far as I can tell, @tonysawfordebi is the only user so far, but I am not against moving the folder from `.gpi` to `gpi`, perhaps with a symlink for backward compatibility.

**Comment by tonysawfordebi** [comment]
I'm quite happy for the folder to be renamed to gpi - all I need to know is when it's been done so I can make the one-character change to my script that retrieves & processes the file.

**Comment by AntonPetrov** [comment]
**Done!** I renamed `.gpi` folder to `gpi` and also included a symlink pointing `.gpi` to `gpi` so that @tonysawfordebi has time to update his programs.

 In the next RNAcentral release (due in ~4 weeks) there will be only one folder, `gpi`:
*ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/gpi*

I hope this helps! Feel free to reopen this issue if necessary.
